import Head from "next/head";

import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";
import Image from "next/image";
import Individual_grade from "@/components/Individual_grade";
import { useState } from "react";
import img1 from "../images/profile.png";
import img2 from "../images/profile2.png";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [show, setShow] = useState<string>("not-graded");
  return (
    <>
      <Head>
        <title>MEDHAVHI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-[#9A9A9A]/10 min-h-screen w-full">
        {/* navbar  */}
        <Navbar />

        {/* main body top part  */}
        <section className="p-[24px] font-urbanist">
          <div className="bg-white p-[1.5rem]  rounded-[1rem]">
            {/* top section */}
            <div className="flex items-start justify-between">
              {/*top section  left part  */}
              <div className="flex items-start space-x-[16px]">
                <div className="flex items-center justify-center h-[60px] w-[60px] rounded-[4px] border shadow-lg border-gray-200">
                  {" "}
                  <p className="text-red-400 text-[12px]  font-urbanist">Sc</p>
                </div>
                <div className="flex flex-col gap-y-2">
                  <p className="text-[16px] font-[500] font-urbanist leading-[20px]">
                    Lorem ipsum dolor sit amet consectetur. Scelerisque aenean
                    nibh.
                  </p>
                  <div className="flex items-center space-x-[1rem]">
                    <div className="flex items-center space-x-[0.5rem]">
                      <p className="text-[14px]">Submmited By : </p>
                      <div className="flex items-center relative">
                        <div className="h-[25px] w-[25px] relative object-contain  z-0">
                          <Image
                            src="https://images.pexels.com/photos/15568433/pexels-photo-15568433.jpeg?auto=compress&cs=tinysrgb&w=600"
                            alt="image"
                            fill
                            className="rounded-full"
                          />
                        </div>
                        <div className="h-[25px] w-[25px] relative object-contain ml-[-10px] z-10">
                          <Image
                            src="https://images.pexels.com/photos/12659913/pexels-photo-12659913.jpeg?auto=compress&cs=tinysrgb&w=600"
                            alt="image"
                            fill
                            className="rounded-full"
                          />
                        </div>
                        <div className="h-[25px] w-[25px] relative object-contain ml-[-10px] z-20">
                          <Image
                            src="https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=600"
                            alt="image"
                            fill
                            className="rounded-full"
                          />
                        </div>
                        <div className="h-[25px] w-[25px] rounded-full bg-blue-200 text-[8px] text-blue-500 flex items-center justify-center ml-[-10px] z-30">
                          +2
                        </div>
                      </div>
                    </div>
                    <div className="flex items-center text-[14px] space-x-[0.5rem]">
                      <p>Assigned On: </p>
                      <p className="text-gray-400">14 Apr 2021, 8:43 PM</p>
                    </div>
                  </div>
                </div>
              </div>
              {/* top section right part */}
              <div className="flex items-center border border-green-700 rounded-[12px] pr-[0.5rem] pl-[2px] py-[2px] space-x-[5px]">
                <div className="bg-green-500 h-[20px] w-[20px] flex items-center justify-center rounded-full">
                  <div className="h-[9px] w-[9px] relative object-contain ">
                    <Image src="/hourglass.png" alt="hourglass" fill />
                  </div>
                </div>
                <p className="text-green-500 text-[12px]">4 Days</p>
              </div>
            </div>
            {/* middle section  */}
            <div className="py-[20px]">
              <p className="text-[14px] text-gray-400 leading-[20px] tracking-[0.03em] font-light">
                Lorem ipsum dolor sit amet consectetur. Pulvinar auctor sed
                proin at sem. Diam nisl in morbi id diam felis. Lectus eget sit
                tristique sit magnis pretium nec. Mus fermentum consequat nisl
                volutpat viverra ut at. Lorem tristique dolor cursus euismod mus
                duis. Etiam aliquam ultrices tristique in
              </p>
            </div>
            {/* bottom section */}
            <div className="p-[0.5rem] flex items-start space-x-5 w-[350px] shadow-lg">
              <Image
                src="/powerpoint.png"
                alt="powerpoint"
                height="30"
                width="30"
              />
              <div className="flex flex-col">
                <p className="text-[14px] leading-[19px]">
                  Evolution Chapter Notes
                </p>
                <p className="text-[12px] text-gray-400">32.5MB</p>
              </div>
              <div>
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke-width="1.5"
                  stroke="currentColor"
                  className="w-6 h-6 ml-[2rem]  "
                >
                  <path
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    d="M3 16.5v2.25A2.25 2.25 0 005.25 21h13.5A2.25 2.25 0 0021 18.75V16.5M16.5 12L12 16.5m0 0L7.5 12m4.5 4.5V3"
                  />
                </svg>
              </div>
            </div>
          </div>
        </section>
        {/* main body bottom part  */}
        <section className="px-[24px] py-[16px]  ">
          <div className="bg-white p-[24px] rounded-[1rem] h-[550px]">
            <div className="flex items-center justify-between">
              <div className="flex">
                <div
                  className={`w-[160px] ${
                    show === "graded"
                      ? "bg-transparent text-black"
                      : "bg-primary text-white"
                  }  rounded-[8px] p-[12px] flex items-center justify-center cursor-pointer`}
                  onClick={() => setShow("not-graded")}
                >
                  <p className="font-[400] text-[14px] leading-[20px] ">
                    Not-Graded
                  </p>
                </div>
                <div
                  className={`w-[160px] ${
                    show === "graded" ? "bg-primary text-white" : "text-black"
                  } rounded-[8px] p-[12px]  flex items-center justify-center cursor-pointer`}
                  onClick={() => setShow("graded")}
                >
                  <p className="font-[400] text-[14px] leading-[20px] ">
                    Graded
                  </p>
                </div>
              </div>
              <div className="w-[250px] bg-gray-200 flex items-center px-[16px] space-x-3 py-[8px] rounded-xl text-gray-500">
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke-width="1.5"
                  stroke="currentColor"
                  className="w-4 h-4"
                >
                  <path
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    d="M21 21l-5.197-5.197m0 0A7.5 7.5 0 105.196 5.196a7.5 7.5 0 0010.607 10.607z"
                  />
                </svg>
                <p className="font-[400] text-[14px] ">Search</p>
              </div>
            </div>
            {/* main body bottom part main section  */}
            <div className="py-[1rem]">
              <Individual_grade
                grade={`${show === "graded" ? "yes" : "no"}`}
                profile={img1}
                submitted="on time"
              />
              <Individual_grade
                grade={`${show === "graded" ? "yes" : "no"}`}
                profile={img2}
                submitted="late submission"
              />
              <Individual_grade
                grade={`${show === "graded" ? "yes" : "no"}`}
                profile={img1}
                submitted="on time"
              />
              <Individual_grade
                grade={`${show === "graded" ? "yes" : "no"}`}
                profile={img2}
                submitted="late submission"
              />
            </div>
          </div>
        </section>
      </main>
    </>
  );
}
